"use strict";
module.exports.application_id 	= 	'5773a2a95d5a2928c000001f';
module.exports.app_user_ip 		= 	'216.117.56.68';
module.exports.mongoUrl 		= 	'mongodb://localhost:27017/teamr';
module.exports.secret 			= 	'comser';
module.exports.devList 			= 	['m','w','t'];
module.exports.appConfig 		= 	{ 'host':'localhost','port': 8081 };
// module.exports.baseURL 			= 	"https://brisol.net/ss2-d/api/";
module.exports.baseURL 			= 	"https://brisol.net/vh2-d/api/";
// module.exports.baseURL 			= 	"http://10.10.21.181/api/api/";